[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
logos = "0.12.1"

[features]
default = ["repl", "prelude"]
repl = []
prelude = []

[[bin]]
name = "lambda"
required-features = ["repl"]